In [68]:
import pandas as pd
import numpy as np

In [69]:
group_sports = pd.read_excel('2020_gry_zespolowe.xlsx',"TABLICA")
group_sports

,Kod,Nazwa,baseball,Unnamed: 3,hokej na lodzie (łącznie z hokejem na łyżworolkach),Unnamed: 5,hokej na trawie,Unnamed: 7,koszykówka,Unnamed: 9,...,piłka siatkowa (łącznie z plażową),Unnamed: 15,piłka wodna,Unnamed: 17,rugby,Unnamed: 19,unihokej,Unnamed: 21,football amerykański,Unnamed: 23
0,NaN,NaN,ogółem,juniorzy,ogółem,juniorzy,ogółem,juniorzy,ogółem,juniorzy,...,ogółem,juniorzy,ogółem,juniorzy,ogółem,juniorzy,ogółem,juniorzy,ogółem,juniorzy
1,NaN,NaN,2020,2020,2020,2020,2020,2020,2020,2020,...,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020
2,NaN,NaN,[osoba],[osoba],[osoba],[osoba],[osoba],[osoba],[osoba],[osoba],...,[osoba],[osoba],[osoba],[osoba],[osoba],[osoba],[osoba],[osoba],[osoba],[osoba]
3,0.0,POLSKA,737,476,4787,2910,2914,2328,38784,33811,...,67776,56012,887,777,3026,1895,7326,6647,1029,334
4,200000.0,DOLNOŚLĄSKIE,142,75,214,84,200,111,2828,2401,...,3621,2974,0,0,79,47,79,79,100,30
5,400000.0,KUJAWSKO-POMORSKIE,85,85,183,45,673,507,3014,2626,...,3740,3047,0,0,113,54,460,454,246,98
6,600000.0,LUBELSKIE,0,0,126,87,0,0,1511,1426,...,3908,3232,0,0,343,277,53,27,72,22
7,800000.0,LUBUSKIE,31,31,0,0,0,0,1413,1293,...,1925,1438,157,150,45,14,215,144,0,0
8,1000000.0,ŁÓDZKIE,87,65,28,12,225,178,2512,2204,...,4450,3516,226,186,400,278,346,344,30,0
9,1200000.0,MAŁOPOLSKIE,19,0,879,539,0,0,3187,2639,...,7740,6338,0,0,163,128,505,327,56,0
10,1400000.0,MAZOWIECKIE,30,0,143,81,45,33,6400,5673,...,9169,7642,159,146,481,326,1229,1163,16,8
11,1600000.0,OPOLSKIE,29,29,97,93,140,140,952,747,...,1178,893,0,0,0,0,63,60,41,0
12,1800000.0,PODKARPACKIE,0,0,18,18,0,0,2177,1916,...,5512,4511,0,0,20,0,809,742,64,26
13,2000000.0,PODLASKIE,18,0,65,25,0,0,1616,1482,...,1927,1615,0,0,65,34,217,201,100,36
14,2200000.0,POMORSKIE,0,0,387,172,0,0,2090,1916,...,3237,2848,0,0,407,255,1069,1066,0,0
15,2400000.0,ŚLĄSKIE,184,106,2330,1651,551,474,3665,3235,...,8238,6632,0,0,295,118,203,107,194,49
16,2600000.0,ŚWIĘTOKRZYSKIE,0,0,30,5,0,0,257,214,...,1547,1366,45,35,0,0,20,20,0,0
17,2800000.0,WARMIŃSKO-MAZURSKIE,100,85,65,47,0,0,1062,943,...,2101,1916,0,0,182,107,276,256,70,25
18,3000000.0,WIELKOPOLSKIE,0,0,197,50,1046,851,4446,3598,...,6204,5191,0,0,348,232,1382,1277,0,0
19,3200000.0,ZACHODNIOPOMORSKIE,12,0,25,1,34,34,1654,1498,...,3279,2853,300,260,85,25,400,380,40,40

In [70]:
other = pd.read_excel('2020_pozostale.xlsx',"TABLICA")
other

,Kod,Nazwa,akrobatyka (łącznie ze skokami na trampolinie),Unnamed: 3,alpinizm,Unnamed: 5,badminton,Unnamed: 7,orientacja sportowa,Unnamed: 9,...,szachy,Unnamed: 43,taniec sportowy,Unnamed: 45,tenis stołowy,Unnamed: 47,tenis,Unnamed: 49,warcaby,Unnamed: 51
0,NaN,NaN,ogółem,juniorzy,ogółem,juniorzy,ogółem,juniorzy,ogółem,juniorzy,...,ogółem,juniorzy,ogółem,juniorzy,ogółem,juniorzy,ogółem,juniorzy,ogółem,juniorzy
1,NaN,NaN,2020,2020,2020,2020,2020,2020,2020,2020,...,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020
2,NaN,NaN,[osoba],[osoba],[osoba],[osoba],[osoba],[osoba],[osoba],[osoba],...,[osoba],[osoba],[osoba],[osoba],[osoba],[osoba],[osoba],[osoba],[osoba],[osoba]
3,0.0,POLSKA,10063,9650,4931,906,7785,6039,2291,1438,...,17025,12207,10237,8807,23215,15800,21399,14224,1411,664
4,200000.0,DOLNOŚLĄSKIE,1125,1102,213,65,381,301,229,142,...,2158,1509,439,331,1731,878,2509,1119,78,21
5,400000.0,KUJAWSKO-POMORSKIE,444,443,297,9,220,172,36,4,...,724,419,1001,909,1354,841,1028,689,80,64
6,600000.0,LUBELSKIE,146,125,88,26,368,266,50,45,...,844,674,94,94,1622,1147,637,417,3,3
7,800000.0,LUBUSKIE,1048,1046,58,1,252,152,42,26,...,634,403,602,580,583,313,293,219,0,0
8,1000000.0,ŁÓDZKIE,239,233,109,69,181,151,265,168,...,600,467,1333,1211,1497,1021,1133,943,156,98
9,1200000.0,MAŁOPOLSKIE,631,610,1673,258,939,716,206,170,...,1519,1323,844,643,2085,1499,2581,1755,0,0
10,1400000.0,MAZOWIECKIE,2861,2790,85,44,769,531,480,201,...,1181,808,2939,2508,2783,2075,4759,3239,173,79
11,1600000.0,OPOLSKIE,42,42,166,22,312,250,111,108,...,146,87,380,314,511,287,523,229,23,0
12,1800000.0,PODKARPACKIE,926,884,68,10,861,665,40,35,...,1430,993,187,172,2080,1524,838,599,92,59
13,2000000.0,PODLASKIE,0,0,0,0,390,319,30,18,...,310,269,112,100,685,464,280,165,70,20
14,2200000.0,POMORSKIE,388,357,97,86,296,265,177,111,...,1277,736,245,211,1176,806,607,327,98,24
15,2400000.0,ŚLĄSKIE,1519,1329,1655,215,834,628,167,106,...,1875,1441,578,499,2489,1718,2089,1847,48,13
16,2600000.0,ŚWIĘTOKRZYSKIE,34,34,130,6,560,528,0,0,...,810,697,15,15,342,234,192,181,0,0
17,2800000.0,WARMIŃSKO-MAZURSKIE,0,0,42,42,85,58,61,20,...,450,344,231,165,682,556,372,205,74,0
18,3000000.0,WIELKOPOLSKIE,361,356,199,12,988,800,186,122,...,2348,1527,728,595,2612,1749,2616,1677,503,270
19,3200000.0,ZACHODNIOPOMORSKIE,299,299,51,41,349,237,211,162,...,719,510,509,460,983,688,942,613,13,13

In [71]:
matrial_arts = pd.read_excel('2020_spoty_walki.xlsx',"TABLICA")
matrial_arts

,Kod,Nazwa,boks,Unnamed: 3,judo,Unnamed: 5,karate,Unnamed: 7,karate tradycyjne,Unnamed: 9,...,jujitsu,Unnamed: 23,kendo,Unnamed: 25,muaythai,Unnamed: 27,sumo,Unnamed: 29,wu-shu,Unnamed: 31
0,NaN,NaN,ogółem,juniorzy,ogółem,juniorzy,ogółem,juniorzy,ogółem,juniorzy,...,ogółem,juniorzy,ogółem,juniorzy,ogółem,juniorzy,ogółem,juniorzy,ogółem,juniorzy
1,NaN,NaN,2020,2020,2020,2020,2020,2020,2020,2020,...,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020
2,NaN,NaN,[osoba],[osoba],[osoba],[osoba],[osoba],[osoba],[osoba],[osoba],...,[osoba],[osoba],[osoba],[osoba],[osoba],[osoba],[osoba],[osoba],[osoba],[osoba]
3,0.0,POLSKA,9327,5766,26362,24739,34118,26955,12048,9831,...,7011,4110,500,137,1158,477,1696,1557,856,502
4,200000.0,DOLNOŚLĄSKIE,725,436,1552,1445,2438,1664,776,707,...,388,147,53,3,10,0,164,150,0,0
5,400000.0,KUJAWSKO-POMORSKIE,683,549,768,690,1686,1365,998,835,...,247,153,0,0,0,0,20,20,17,17
6,600000.0,LUBELSKIE,399,274,307,297,1319,1067,735,701,...,609,420,0,0,20,0,44,29,30,24
7,800000.0,LUBUSKIE,290,153,456,451,627,514,126,105,...,408,199,0,0,42,16,84,78,0,0
8,1000000.0,ŁÓDZKIE,636,337,1018,970,1658,1336,1739,1483,...,119,67,49,26,56,47,201,175,0,0
9,1200000.0,MAŁOPOLSKIE,692,372,1901,1760,3026,2322,1177,874,...,569,459,25,4,118,69,44,44,497,323
10,1400000.0,MAZOWIECKIE,1035,538,8150,7811,5012,4133,1425,1241,...,577,211,94,55,429,142,229,211,125,64
11,1600000.0,OPOLSKIE,10,5,865,828,1368,1096,504,411,...,130,74,0,0,50,25,14,14,0,0
12,1800000.0,PODKARPACKIE,192,149,687,634,2134,1686,910,802,...,329,211,0,0,0,0,55,38,0,0
13,2000000.0,PODLASKIE,506,272,996,835,1039,845,175,85,...,139,49,131,14,121,67,63,58,0,0
14,2200000.0,POMORSKIE,453,355,1569,1534,1302,1107,1268,943,...,260,6,38,6,0,0,46,43,5,0
15,2400000.0,ŚLĄSKIE,1602,834,4978,4629,4232,3196,498,341,...,1860,1328,50,13,157,29,0,0,132,50
16,2600000.0,ŚWIĘTOKRZYSKIE,296,202,153,129,1083,871,370,200,...,0,0,0,0,0,0,120,120,15,10
17,2800000.0,WARMIŃSKO-MAZURSKIE,214,131,480,435,1201,959,97,92,...,205,132,7,1,15,0,24,24,35,14
18,3000000.0,WIELKOPOLSKIE,922,680,1987,1841,3760,2960,704,538,...,731,366,45,14,112,72,275,260,0,0
19,3200000.0,ZACHODNIOPOMORSKIE,672,479,495,450,2233,1834,546,473,...,440,288,8,1,28,10,313,293,0,0

In [72]:
water_sports = pd.read_excel('2020_spoty_wodne.xlsx',"TABLICA")
water_sports

,Kod,Nazwa,kajakarstwo górskie,Unnamed: 3,kajakarstwo klasyczne,Unnamed: 5,narciarstwo wodne,Unnamed: 7,pływanie,Unnamed: 9,skoki do wody,Unnamed: 11,wędkarstwo,Unnamed: 13,wioślarstwo,Unnamed: 15,żeglarstwo (łodzie regatowe),Unnamed: 17,żeglarstwo deskowe (letnie),Unnamed: 19
0,NaN,NaN,ogółem,juniorzy,ogółem,juniorzy,ogółem,juniorzy,ogółem,juniorzy,ogółem,juniorzy,ogółem,juniorzy,ogółem,juniorzy,ogółem,juniorzy,ogółem,juniorzy
1,NaN,NaN,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020
2,NaN,NaN,[osoba],[osoba],[osoba],[osoba],[osoba],[osoba],[osoba],[osoba],[osoba],[osoba],[osoba],[osoba],[osoba],[osoba],[osoba],[osoba],[osoba],[osoba]
3,0.0,POLSKA,582,341,3346,2463,158,98,48407,45002,512,340,1125,96,2330,1677,6935,4227,609,441
4,200000.0,DOLNOŚLĄSKIE,39,4,56,30,20,10,4508,4122,0,0,15,0,107,86,247,171,0,0
5,400000.0,KUJAWSKO-POMORSKIE,1,0,465,434,8,7,3179,3054,0,0,4,4,661,504,414,212,63,17
6,600000.0,LUBELSKIE,0,0,71,55,5,0,1915,1804,120,120,0,0,0,0,53,40,0,0
7,800000.0,LUBUSKIE,0,0,250,218,0,0,552,517,0,0,0,0,52,39,85,57,0,0
8,1000000.0,ŁÓDZKIE,98,92,84,71,0,0,2521,2217,0,0,24,0,0,0,30,30,0,0
9,1200000.0,MAŁOPOLSKIE,332,171,225,165,0,0,3797,3475,0,0,12,0,184,107,412,352,0,0
10,1400000.0,MAZOWIECKIE,69,54,143,105,3,3,8389,8017,110,92,52,0,325,174,649,430,33,32
11,1600000.0,OPOLSKIE,0,0,59,23,0,0,669,522,0,0,213,20,0,0,103,69,0,0
12,1800000.0,PODKARPACKIE,0,0,65,45,0,0,2687,2567,42,41,16,0,0,0,116,49,0,0
13,2000000.0,PODLASKIE,30,20,94,56,65,44,1064,974,0,0,31,0,0,0,357,155,0,0
14,2200000.0,POMORSKIE,0,0,341,237,0,0,1930,1833,0,0,85,3,261,172,1350,844,208,191
15,2400000.0,ŚLĄSKIE,13,0,528,300,40,29,7688,7314,64,51,239,37,36,24,994,630,0,0
16,2600000.0,ŚWIĘTOKRZYSKIE,0,0,60,20,7,5,840,840,0,0,14,0,0,0,27,15,0,0
17,2800000.0,WARMIŃSKO-MAZURSKIE,0,0,136,89,0,0,1587,1266,0,0,0,0,151,145,342,306,0,0
18,3000000.0,WIELKOPOLSKIE,0,0,565,420,10,0,4897,4337,176,36,420,32,407,353,952,507,107,86
19,3200000.0,ZACHODNIOPOMORSKIE,0,0,204,195,0,0,2184,2143,0,0,0,0,146,73,804,360,198,115

In [73]:
winter_sports = pd.read_excel('2020_spoty_zimowe.xlsx',"TABLICA")
winter_sports

,Kod,Nazwa,biathlon zimowy,Unnamed: 3,łyżwiarstwo figurowe,Unnamed: 5,łyżwiarstwo szybkie (łącznie z short track),Unnamed: 7,narciarstwo alpejskie,Unnamed: 9,narciarstwo klasyczne,Unnamed: 11,snowboard,Unnamed: 13,sport saneczkowy,Unnamed: 15
0,NaN,NaN,ogółem,juniorzy,ogółem,juniorzy,ogółem,juniorzy,ogółem,juniorzy,ogółem,juniorzy,ogółem,juniorzy,ogółem,juniorzy
1,NaN,NaN,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020
2,NaN,NaN,[osoba],[osoba],[osoba],[osoba],[osoba],[osoba],[osoba],[osoba],[osoba],[osoba],[osoba],[osoba],[osoba],[osoba]
3,0.0,POLSKA,865,727,2176,1972,1954,1696,4270,3252,3242,2647,567,335,293,197
4,200000.0,DOLNOŚLĄSKIE,352,338,72,56,174,164,350,314,250,220,82,62,51,34
5,400000.0,KUJAWSKO-POMORSKIE,0,0,254,216,0,0,0,0,15,0,12,0,0,0
6,600000.0,LUBELSKIE,0,0,0,0,0,0,173,162,231,194,0,0,0,0
7,800000.0,LUBUSKIE,0,0,0,0,140,100,0,0,0,0,0,0,93,60
8,1000000.0,ŁÓDZKIE,0,0,369,351,441,396,42,42,27,11,0,0,0,0
9,1200000.0,MAŁOPOLSKIE,178,163,252,244,152,140,1231,1077,1218,1099,192,117,23,22
10,1400000.0,MAZOWIECKIE,108,108,532,461,376,306,353,202,255,234,67,44,54,54
11,1600000.0,OPOLSKIE,0,0,36,36,20,12,7,0,27,10,5,0,0,0
12,1800000.0,PODKARPACKIE,41,24,22,22,163,156,566,489,373,268,4,4,0,0
13,2000000.0,PODLASKIE,0,0,0,0,238,230,3,1,88,75,0,0,0,0
14,2200000.0,POMORSKIE,0,0,207,176,27,17,0,0,11,9,0,0,31,4
15,2400000.0,ŚLĄSKIE,186,94,291,269,9,2,1444,896,719,499,175,98,40,23
16,2600000.0,ŚWIĘTOKRZYSKIE,0,0,0,0,0,0,73,63,13,13,0,0,0,0
17,2800000.0,WARMIŃSKO-MAZURSKIE,0,0,126,126,214,173,0,0,0,0,0,0,1,0
18,3000000.0,WIELKOPOLSKIE,0,0,15,15,0,0,24,6,15,15,30,10,0,0
19,3200000.0,ZACHODNIOPOMORSKIE,0,0,0,0,0,0,4,0,0,0,0,0,0,0

In [74]:
path_dict = {
    "group_sports": r"2020_gry_zespolowe.xlsx",
    "other": r'2020_pozostale.xlsx',
    "matrial_arts": r"2020_spoty_walki.xlsx",
    "water_sports": r"2020_spoty_wodne.xlsx",
    "winter_sports": r"2020_spoty_zimowe.xlsx"
}

In [75]:
def load_data() -> Tuple[DataFrame]:
    '''This method loads data from xlsx file to dataframe and removes unnecessary fields'''
    group_sports = pd.read_excel(path_dict['group_sports'],"TABLICA")
    other = pd.read_excel(path_dict["other"],"TABLICA")
    matrial_arts = pd.read_excel(path_dict["matrial_arts"],"TABLICA")
    water_sports = pd.read_excel(path_dict["water_sports"],"TABLICA")
    winter_sports = pd.read_excel(path_dict['winter_sports'],"TABLICA")
        
    new_group = group_sports[[x for x in group_sports.columns if "Unnamed" not in x]].copy().iloc[3:].drop(columns=["Kod"])
    new_other = other[[x for x in other.columns if "Unnamed" not in x]].copy().iloc[3:].drop(columns=["Kod"])
    new_matrial_arts = matrial_arts[[x for x in matrial_arts.columns if "Unnamed" not in x]].copy().iloc[3:].drop(columns=["Kod"])
    new_water = water_sports[[x for x in water_sports.columns if "Unnamed" not in x]].copy().iloc[3:].drop(columns=["Kod"])
    new_winter = winter_sports[[x for x in winter_sports.columns if "Unnamed" not in x]].copy().iloc[3:].drop(columns=["Kod"])
        
    return (new_group, new_other, new_matrial_arts, new_water, new_winter)

In [76]:
def calculate_total_athletes():
    data = load_data()
    names = data[0]["Nazwa"].to_frame()
    print(names)
    sum_group = names.join(data[0].drop(columns=["Nazwa"]).sum(axis = 1, skipna = True).to_frame()).rename(columns = {0:"Sporty grupowe"})
    sum_other = names.join(data[1].drop(columns=["Nazwa"]).sum(axis = 1, skipna = True).to_frame()).rename(columns = {0:"Pozostale"})
    sum_matrial_arts = names.join(data[2].drop(columns=["Nazwa"]).sum(axis = 1, skipna = True).to_frame()).rename(columns = {0:"Sporty walki"})
    sum_water = names.join(data[3].drop(columns=["Nazwa"]).sum(axis = 1, skipna = True).to_frame()).rename(columns = {0:"Sporty wodne"})
    sum_winter = names.join(data[4].drop(columns=["Nazwa"]).sum(axis = 1, skipna = True).to_frame()).rename(columns = {0:"Sporty zimowe"})
    total = sum_group.join(sum_other["Pozostale"]).join(sum_matrial_arts["Sporty walki"]).join(sum_water["Sporty wodne"]).join(sum_winter["Sporty zimowe"])
    total['Total'] = total.sum(axis=1)
    total.reset_index(inplace=True, drop=True)
    total.drop([0],inplace=True)
    total.reset_index(inplace=True, drop=True)
    voivodeships = total[["Nazwa","Total"]]
    return voivodeships

In [77]:
def join_all_sports() -> DataFrame:   
    data = load_data()
    names = data[0]["Nazwa"].to_frame()
    all_sports = names.join(data[0].drop(columns=["Nazwa"])).join(data[1].drop(columns=["Nazwa"])).join(data[2].drop(columns=["Nazwa"])).join(data[3].drop(columns=["Nazwa"])).join(data[4].drop(columns=["Nazwa"]))
    all_sports.reset_index(inplace=True, drop=True)
    all_sports.drop([0], inplace=True)
    all_sports.reset_index(inplace=True, drop=True)
    return all_sports

In [78]:
df = join_all_sports().drop(columns=["Nazwa"])
df_name = join_all_sports()
df.to_csv(r'sports_per_voivodship.csv', index = False)
df_name.to_csv(r'all_sports.csv', index = False)