In [1]:
import pandas as pd
import numpy as np
from random import choices

In [2]:
files = ["2020_gry_zespolowe.xlsx", "2020_pozostale.xlsx","2020_spoty_walki.xlsx","2020_spoty_wodne.xlsx","2020_spoty_zimowe.xlsx"]

In [3]:
df_s = [pd.read_excel(file, "TABLICA")
    for file in files]

FileNotFoundError: [Errno 2] No such file or directory: '2020_gry_zespolowe.xlsx'

In [ ]:
df_s[0]

,Kod,Nazwa,baseball,Unnamed: 3,hokej na lodzie (łącznie z hokejem na łyżworolkach),Unnamed: 5,hokej na trawie,Unnamed: 7,koszykówka,Unnamed: 9,...,piłka siatkowa (łącznie z plażową),Unnamed: 15,piłka wodna,Unnamed: 17,rugby,Unnamed: 19,unihokej,Unnamed: 21,football amerykański,Unnamed: 23
0,NaN,NaN,ogółem,juniorzy,ogółem,juniorzy,ogółem,juniorzy,ogółem,juniorzy,...,ogółem,juniorzy,ogółem,juniorzy,ogółem,juniorzy,ogółem,juniorzy,ogółem,juniorzy
1,NaN,NaN,2020,2020,2020,2020,2020,2020,2020,2020,...,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020
2,NaN,NaN,[osoba],[osoba],[osoba],[osoba],[osoba],[osoba],[osoba],[osoba],...,[osoba],[osoba],[osoba],[osoba],[osoba],[osoba],[osoba],[osoba],[osoba],[osoba]
3,0.0,POLSKA,737,476,4787,2910,2914,2328,38784,33811,...,67776,56012,887,777,3026,1895,7326,6647,1029,334
4,200000.0,DOLNOŚLĄSKIE,142,75,214,84,200,111,2828,2401,...,3621,2974,0,0,79,47,79,79,100,30
5,400000.0,KUJAWSKO-POMORSKIE,85,85,183,45,673,507,3014,2626,...,3740,3047,0,0,113,54,460,454,246,98
6,600000.0,LUBELSKIE,0,0,126,87,0,0,1511,1426,...,3908,3232,0,0,343,277,53,27,72,22
7,800000.0,LUBUSKIE,31,31,0,0,0,0,1413,1293,...,1925,1438,157,150,45,14,215,144,0,0
8,1000000.0,ŁÓDZKIE,87,65,28,12,225,178,2512,2204,...,4450,3516,226,186,400,278,346,344,30,0
9,1200000.0,MAŁOPOLSKIE,19,0,879,539,0,0,3187,2639,...,7740,6338,0,0,163,128,505,327,56,0
10,1400000.0,MAZOWIECKIE,30,0,143,81,45,33,6400,5673,...,9169,7642,159,146,481,326,1229,1163,16,8
11,1600000.0,OPOLSKIE,29,29,97,93,140,140,952,747,...,1178,893,0,0,0,0,63,60,41,0
12,1800000.0,PODKARPACKIE,0,0,18,18,0,0,2177,1916,...,5512,4511,0,0,20,0,809,742,64,26
13,2000000.0,PODLASKIE,18,0,65,25,0,0,1616,1482,...,1927,1615,0,0,65,34,217,201,100,36
14,2200000.0,POMORSKIE,0,0,387,172,0,0,2090,1916,...,3237,2848,0,0,407,255,1069,1066,0,0
15,2400000.0,ŚLĄSKIE,184,106,2330,1651,551,474,3665,3235,...,8238,6632,0,0,295,118,203,107,194,49
16,2600000.0,ŚWIĘTOKRZYSKIE,0,0,30,5,0,0,257,214,...,1547,1366,45,35,0,0,20,20,0,0
17,2800000.0,WARMIŃSKO-MAZURSKIE,100,85,65,47,0,0,1062,943,...,2101,1916,0,0,182,107,276,256,70,25
18,3000000.0,WIELKOPOLSKIE,0,0,197,50,1046,851,4446,3598,...,6204,5191,0,0,348,232,1382,1277,0,0
19,3200000.0,ZACHODNIOPOMORSKIE,12,0,25,1,34,34,1654,1498,...,3279,2853,300,260,85,25,400,380,40,40

In [ ]:
juniors_in_voivodeship=pd.DataFrame(np.array([df_s[i].loc[4:,df_s[i].columns[3::2]].sum(axis=1) 
for i in range(len(df_s))]).T).sum(axis=1)
juniors_in_voivodeship

0      53081.0
1      42819.0
2      35301.0
3      17340.0
4      43954.0
5      77925.0
6     108240.0
7      19316.0
8      47744.0
9      19777.0
10     39890.0
11     95810.0
12     14947.0
13     20566.0
14     69327.0
15     35513.0
dtype: float64

In [ ]:
generally_in_voivodeship=pd.DataFrame(np.array([df_s[i].loc[4:,df_s[i].columns[2::2]].sum(axis=1) 
for i in range(len(df_s))]).T).sum(axis=1)
generally_in_voivodeship

0     105783.0
1      56193.0
2      47723.0
3      25821.0
4      61158.0
5     105675.0
6     144651.0
7      31321.0
8      68818.0
9      28028.0
10     52904.0
11    129699.0
12     19355.0
13     29007.0
14    100590.0
15     48597.0
dtype: float64

In [ ]:
x=df_s[0]["Nazwa"][4:]
x.reset_index(inplace=True, drop=True)

result_df = pd.DataFrame({"voivodeship":x,
             "juniors": juniors_in_voivodeship,
              "seniors":generally_in_voivodeship-juniors_in_voivodeship})
result_df

            voivodeship   juniors  seniors
0          DOLNOŚLĄSKIE   53081.0  52702.0
1    KUJAWSKO-POMORSKIE   42819.0  13374.0
2             LUBELSKIE   35301.0  12422.0
3              LUBUSKIE   17340.0   8481.0
4               ŁÓDZKIE   43954.0  17204.0
5           MAŁOPOLSKIE   77925.0  27750.0
6           MAZOWIECKIE  108240.0  36411.0
7              OPOLSKIE   19316.0  12005.0
8          PODKARPACKIE   47744.0  21074.0
9             PODLASKIE   19777.0   8251.0
10            POMORSKIE   39890.0  13014.0
11              ŚLĄSKIE   95810.0  33889.0
12       ŚWIĘTOKRZYSKIE   14947.0   4408.0
13  WARMIŃSKO-MAZURSKIE   20566.0   8441.0
14        WIELKOPOLSKIE   69327.0  31263.0
15   ZACHODNIOPOMORSKIE   35513.0  13084.0

In [ ]:
df_males = pd.read_csv("../people/voivodship_males_by_sexage.csv", index_col='index')
df_females = pd.read_csv("../people/voivodship_females_by_sexage.csv", index_col='index')

In [ ]:
m_add_fem_15_17_df = df_females[15:18].sum(axis=0)+df_males[15:18].sum(axis=0)
m_add_fem_15_17_df.name = "population 15-17yo"

In [ ]:
m_add_fem_18_40_df = df_females[17:41].sum(axis=0)+df_males[17:41].sum(axis=0)
m_add_fem_18_40_df.name = "population 18-40yo"

In [ ]:
merged_df = result_df.merge(pd.DataFrame(m_add_fem_15_17_df), left_on="voivodeship", right_index=True)
merged_df = merged_df.merge(pd.DataFrame(m_add_fem_18_40_df), left_on="voivodeship", right_index=True)
merged_df

,voivodeship,juniors,seniors,population 15-17yo,population 18-40yo
0,DOLNOŚLĄSKIE,53081.0,52702.0,76358,893919
1,KUJAWSKO-POMORSKIE,42819.0,13374.0,60620,649880
2,LUBELSKIE,35301.0,12422.0,61357,663567
3,LUBUSKIE,17340.0,8481.0,29384,315311
4,ŁÓDZKIE,43954.0,17204.0,66345,726034
5,MAŁOPOLSKIE,77925.0,27750.0,100005,1111168
6,MAZOWIECKIE,108240.0,36411.0,157318,1678197
7,OPOLSKIE,19316.0,12005.0,25180,298393
8,PODKARPACKIE,47744.0,21074.0,63573,698127
9,PODLASKIE,19777.0,8251.0,33179,374532
10,POMORSKIE,39890.0,13014.0,70753,751386
11,ŚLĄSKIE,95810.0,33889.0,119563,1343976
12,ŚWIĘTOKRZYSKIE,14947.0,4408.0,33553,377545
13,WARMIŃSKO-MAZURSKIE,20566.0,8441.0,42426,454671
14,WIELKOPOLSKIE,69327.0,31263.0,104294,1117863
15,ZACHODNIOPOMORSKIE,35513.0,13084.0,47567,520643

In [ ]:
merged_df["junior_chance"]=merged_df.juniors/merged_df["population 15-17yo"]
merged_df["senior_chance"]=merged_df.seniors/merged_df["population 18-40yo"]
merged_df

,voivodeship,juniors,seniors,population 15-17yo,population 18-40yo,junior_chance,senior_chance
0,DOLNOŚLĄSKIE,53081.0,52702.0,76358,893919,0.695160,0.058956
1,KUJAWSKO-POMORSKIE,42819.0,13374.0,60620,649880,0.706351,0.020579
2,LUBELSKIE,35301.0,12422.0,61357,663567,0.575338,0.018720
3,LUBUSKIE,17340.0,8481.0,29384,315311,0.590117,0.026897
4,ŁÓDZKIE,43954.0,17204.0,66345,726034,0.662507,0.023696
5,MAŁOPOLSKIE,77925.0,27750.0,100005,1111168,0.779211,0.024974
6,MAZOWIECKIE,108240.0,36411.0,157318,1678197,0.688033,0.021696
7,OPOLSKIE,19316.0,12005.0,25180,298393,0.767117,0.040232
8,PODKARPACKIE,47744.0,21074.0,63573,698127,0.751011,0.030186
9,PODLASKIE,19777.0,8251.0,33179,374532,0.596070,0.022030
10,POMORSKIE,39890.0,13014.0,70753,751386,0.563792,0.017320
11,ŚLĄSKIE,95810.0,33889.0,119563,1343976,0.801335,0.025215
12,ŚWIĘTOKRZYSKIE,14947.0,4408.0,33553,377545,0.445474,0.011675
13,WARMIŃSKO-MAZURSKIE,20566.0,8441.0,42426,454671,0.484750,0.018565
14,WIELKOPOLSKIE,69327.0,31263.0,104294,1117863,0.664727,0.027967
15,ZACHODNIOPOMORSKIE,35513.0,13084.0,47567,520643,0.746589,0.025130

In [ ]:
merged_df.set_index('voivodeship', drop=True, inplace=True)
merged_df

,juniors,seniors,population 15-17yo,population 18-40yo,junior_chance,senior_chance
voivodeship,,,,,,
DOLNOŚLĄSKIE,53081.0,52702.0,76358,893919,0.695160,0.058956
KUJAWSKO-POMORSKIE,42819.0,13374.0,60620,649880,0.706351,0.020579
LUBELSKIE,35301.0,12422.0,61357,663567,0.575338,0.018720
LUBUSKIE,17340.0,8481.0,29384,315311,0.590117,0.026897
ŁÓDZKIE,43954.0,17204.0,66345,726034,0.662507,0.023696
MAŁOPOLSKIE,77925.0,27750.0,100005,1111168,0.779211,0.024974
MAZOWIECKIE,108240.0,36411.0,157318,1678197,0.688033,0.021696
OPOLSKIE,19316.0,12005.0,25180,298393,0.767117,0.040232
PODKARPACKIE,47744.0,21074.0,63573,698127,0.751011,0.030186
PODLASKIE,19777.0,8251.0,33179,374532,0.596070,0.022030
POMORSKIE,39890.0,13014.0,70753,751386,0.563792,0.017320
ŚLĄSKIE,95810.0,33889.0,119563,1343976,0.801335,0.025215
ŚWIĘTOKRZYSKIE,14947.0,4408.0,33553,377545,0.445474,0.011675
WARMIŃSKO-MAZURSKIE,20566.0,8441.0,42426,454671,0.484750,0.018565
WIELKOPOLSKIE,69327.0,31263.0,104294,1117863,0.664727,0.027967
ZACHODNIOPOMORSKIE,35513.0,13084.0,47567,520643,0.746589,0.025130

In [ ]:
# merged_df[merged_df.columns[[-2,-1]]].to_csv("sportman_chance.csv", index=True)